<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PersonnelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $personnel = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'position' => 'Senior Inspector',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP001',
                'email' => 'john.smith@company.com',
                'phone' => '+1-555-0101',
                'supervisor' => 'Mark Johnson',
                'hire_date' => '2020-01-15',
                'experience_years' => 8,
                'qualifications' => 'MT/PT/UT Level III, ASNT Certified',
                'certifications' => 'NDT Level III, ISO 9712, ASNT Level III',
                'notes' => 'Specialized in magnetic particle and ultrasonic testing',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'position' => 'Lead Inspector',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP002',
                'email' => 'sarah.johnson@company.com',
                'phone' => '+1-555-0102',
                'supervisor' => 'Mark Johnson',
                'hire_date' => '2019-03-20',
                'experience_years' => 6,
                'qualifications' => 'VT/PT Level II, LEEA Certified',
                'certifications' => 'LEEA Inspector, NDT Level II, First Aid Certified',
                'notes' => 'Expert in visual and penetrant testing, lifting equipment specialist',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Wilson',
                'position' => 'Inspector',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP003',
                'email' => 'michael.wilson@company.com',
                'phone' => '+1-555-0103',
                'supervisor' => 'Sarah Johnson',
                'hire_date' => '2021-07-10',
                'experience_years' => 4,
                'qualifications' => 'MT/VT Level II, Crane Inspector',
                'certifications' => 'NDT Level II, Crane Inspector Certification',
                'notes' => 'Focuses on magnetic particle testing and crane inspections',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Emma',
                'last_name' => 'Davis',
                'position' => 'Senior Inspector',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP004',
                'email' => 'emma.davis@company.com',
                'phone' => '+1-555-0104',
                'supervisor' => 'Mark Johnson',
                'hire_date' => '2018-11-05',
                'experience_years' => 10,
                'qualifications' => 'RT/UT/MT Level III, Welding Inspector',
                'certifications' => 'AWS CWI, NDT Level III, ASME Certified',
                'notes' => 'Radiographic testing specialist, welding inspector',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Brown',
                'position' => 'Inspector',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP005',
                'email' => 'david.brown@company.com',
                'phone' => '+1-555-0105',
                'supervisor' => 'Emma Davis',
                'hire_date' => '2022-02-14',
                'experience_years' => 3,
                'qualifications' => 'VT/PT Level II, Safety Officer',
                'certifications' => 'NDT Level II, NEBOSH Safety Certificate',
                'notes' => 'Visual testing expert with safety specialization',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Garcia',
                'position' => 'Lifting Specialist',
                'department' => 'Lifting Equipment',
                'employee_id' => 'EMP006',
                'email' => 'lisa.garcia@company.com',
                'phone' => '+1-555-0106',
                'supervisor' => 'Robert Martinez',
                'hire_date' => '2020-06-01',
                'experience_years' => 7,
                'qualifications' => 'LEEA Qualified, Load Testing Certified',
                'certifications' => 'LEEA Inspector, Load Test Engineer, LOLER Certified',
                'notes' => 'Specialized in lifting equipment inspection and load testing',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Martinez',
                'position' => 'Senior Lifting Engineer',
                'department' => 'Lifting Equipment',
                'employee_id' => 'EMP007',
                'email' => 'robert.martinez@company.com',
                'phone' => '+1-555-0107',
                'supervisor' => 'Mark Johnson',
                'hire_date' => '2017-09-12',
                'experience_years' => 12,
                'qualifications' => 'LEEA Qualified Engineer, Structural Engineer',
                'certifications' => 'LEEA Engineer, PE License, Load Test Supervisor',
                'notes' => 'Lead engineer for lifting equipment design and testing',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Jennifer',
                'last_name' => 'Lopez',
                'position' => 'Quality Technician',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP008',
                'email' => 'jennifer.lopez@company.com',
                'phone' => '+1-555-0108',
                'supervisor' => 'Sarah Johnson',
                'hire_date' => '2023-01-20',
                'experience_years' => 2,
                'qualifications' => 'VT Level I, Quality Control',
                'certifications' => 'NDT Level I, Quality Control Certificate',
                'notes' => 'Entry-level technician specializing in visual inspection',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'William',
                'last_name' => 'Taylor',
                'position' => 'Load Test Engineer',
                'department' => 'Testing',
                'employee_id' => 'EMP009',
                'email' => 'william.taylor@company.com',
                'phone' => '+1-555-0109',
                'supervisor' => 'Robert Martinez',
                'hire_date' => '2019-08-30',
                'experience_years' => 9,
                'qualifications' => 'Load Testing Engineer, Structural Analysis',
                'certifications' => 'PE License, Load Test Certified, FEA Specialist',
                'notes' => 'Expert in load testing procedures and structural analysis',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Mary',
                'last_name' => 'Anderson',
                'position' => 'QA Supervisor',
                'department' => 'Quality Assurance',
                'employee_id' => 'EMP010',
                'email' => 'mary.anderson@company.com',
                'phone' => '+1-555-0110',
                'supervisor' => 'Mark Johnson',
                'hire_date' => '2016-04-18',
                'experience_years' => 15,
                'qualifications' => 'Quality Management, ISO Auditor',
                'certifications' => 'ISO 9001 Lead Auditor, Six Sigma Black Belt',
                'notes' => 'Quality systems supervisor and ISO auditor',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('personnels')->insert($personnel);
    }
}
